server:
  port: 8092
spring:
  application:
    name: hotel-api
  datasource:
    url: jdbc:h2:mem:hoteldb
    driver-class-name: org.h2.Driver
    username: username
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true